# -*- coding: utf-8 -*-
"""updatedTask8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17efd72fWI0PHsXieBjE0NM5eMCK6rRy-
"""

from typing import Dict, Any

Customer = Dict[str, Any]

def compute_loyalty_points(net_total: float, customer: Customer) -> int:


    base_points = int(net_total // 5)

    tier = customer.get("tier", "").upper()
    if tier == "GOLD":
        bonus = int(base_points * 0.20)
    elif tier == "SILVER":
        bonus = int(base_points * 0.10)
    else:
        bonus = 0

    total_points = base_points + bonus

    return total_points